update to match summer 18 interface
forcedotcom/LightningFlowComponents pull request #2
Opened 2018-05-17 10:07 UTC by amagnier-sfdc

2018-05-17 12:12 UTC, cchabanois-sfdc requested changes

2018-05-17 12:12 UTC, cchabanois-sfdc commented on flow_local_actions/LoadWebPage/force-app/main/default/aura/loadWebPage/loadWebPageController.js
>  	    		destUrl = 'http://' + destUrl;
you should not use tabs

2018-05-17 12:42 UTC, amagnier-sfdc commented on flow_local_actions/LoadWebPage/force-app/main/default/aura/loadWebPage/loadWebPageController.js
>  	    		destUrl = 'http://' + destUrl;
done

2018-05-18 08:25 UTC, cchabanois-sfdc approved these changes

2018-05-18 08:25 UTC, merged